require: standard

inherit_gem: 
  syntax_tree: config/rubocop.yml
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "Gemfile"
    - "bin/*"
    - "config/puma.rb"
    - "config/environments/**.rb"